spring:
  application:
    name: baron-test
  datasource:
    url: jdbc:mysql://localhost:3306/test-product-wms?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 18080
  servlet:
    context-path: /wms

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  database:
    type: mysql

baron:
  debug: true
  resources:
    package: ''
  upload:
    file-path: C:/images